### ISSUE TITLE
Python 3.5, OSX 10.11 and Qt5: neither cx_freeze 4.3.4 nor 5.0 work, but...

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#170]
Originally reported by: **uliano guerrini (Bitbucket: [uguerrini](https://bitbucket.org/uguerrini), GitHub: Unknown)**

----------------------------------------

this is the test code 

```
#!python

import sys
from PyQt5.QtWidgets import QApplication, QDialog

app = QApplication(sys.argv)
form = QDialog()
form.show()
app.exec_()

```

this is the setup

```
#!python

import sys
from cx_Freeze import setup, Executable

base = 'Console'
if sys.platform == 'win32':
    base = 'Win32GUI'

options = {
    'build_exe': {
        'excludes': ['Tkinter'],  
    } 
}

executables = [
    Executable('PyQt5app.py', base=base)
]

setup(name='PyQt5app',
      version='0.1',
      description='Sample PyQt5 GUI',
      executables=executables,
      options=options
      )


```

and this is the invocation

```
#!bash

python3 setup.py bdist_mac --qt-menu-nib=/usr/local/Cellar/qt5/5.5.1_2/plugins/platforms/

```

with 4.3.4 I get:

```
#!

uliano@MacPro:~/PycharmProjects/freezeqt5$ ./build/PyQt5app-0.1.app/Contents/MacOS/PyQt5app 
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py", line 1140, in _install
    import _frozen_importlib_external
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py", line 969, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py", line 956, in _find_and_load_unlocked
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_frozen_importlib_external'
Fatal Python error: Py_Initialize: importlib install failed

Current thread 0x00007fff75417000 (most recent call first):
Abort trap: 6

```

with 5.0 I get 

```
#!
uliano@MacPro:~/PycharmProjects/freezeqt5$ ./build/PyQt5app-0.1.app/Contents/MacOS/PyQt5app 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
    exec(code, m.__dict__)
  File "PyQt5app.py", line 2, in <module>
    from PyQt5.QtWidgets import QApplication, QDialog
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
  File "ExtensionLoader_PyQt5_QtWidgets.py", line 3, in __bootstrap__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 19, in <module>
    from importlib._bootstrap import _ERR_MSG, _exec, _load, _builtin_from_name
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 57, in <module>
    import types
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py", line 13, in <module>
    import heapq as _heapq
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/heapq.py", line 587, in <module>
    from _heapq import *
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "ExtensionLoader__heapq.py", line 22, in <module>
  File "ExtensionLoader__heapq.py", line 14, in __bootstrap__
AttributeError: module 'imp' has no attribute 'load_dynamic'


```
but if i run first 4.3.4 and then 5.0 without deleting ./build in between, well...
# **then it runs !!?** #

the directory structure changes quite a bit between 4.3.4:

```
#!

uliano@MacPro:~/PycharmProjects/freezeqt5$ tree build/PyQt5app-0.1.app/Contents/MacOS/
build/PyQt5app-0.1.app/Contents/MacOS/
├── PyQt5.QtCore.so
├── PyQt5.QtGui.so
├── PyQt5.QtWidgets.so
├── PyQt5app
├── Python
├── QtCore
├── QtCore.so
├── QtGui
├── QtGui.so
├── QtPrintSupport
├── QtWidgets
├── QtWidgets.so
├── _bz2.cpython-35m-darwin.so
├── _codecs_cn.cpython-35m-darwin.so
├── _codecs_hk.cpython-35m-darwin.so
├── _codecs_iso2022.cpython-35m-darwin.so
├── _codecs_jp.cpython-35m-darwin.so
├── _codecs_kr.cpython-35m-darwin.so
├── _codecs_tw.cpython-35m-darwin.so
├── _datetime.cpython-35m-darwin.so
├── _heapq.cpython-35m-darwin.so
├── _multibytecodec.cpython-35m-darwin.so
├── _struct.cpython-35m-darwin.so
├── binascii.cpython-35m-darwin.so
├── imageformats
│   ├── libqdds.dylib
│   ├── libqgif.dylib
│   ├── libqicns.dylib
│   ├── libqico.dylib
│   ├── libqjp2.dylib
│   ├── libqjpeg.dylib
│   ├── libqmng.dylib
│   ├── libqsvg.dylib
│   ├── libqtga.dylib
│   ├── libqtiff.dylib
│   ├── libqwbmp.dylib
│   └── libqwebp.dylib
├── library.zip
├── math.cpython-35m-darwin.so
├── platforms
│   ├── libqcocoa.dylib
│   ├── libqminimal.dylib
│   └── libqoffscreen.dylib
├── sip.so
├── unicodedata.cpython-35m-darwin.so
└── zlib.cpython-35m-darwin.so

2 directories, 44 files

```

and 5.0

```
#!

uliano@MacPro:~/PycharmProjects/freezeqt5$ tree build5/PyQt5app-0.1.app/Contents/MacOS/
build5/PyQt5app-0.1.app/Contents/MacOS/
├── PyQt5app
├── Python
├── QtCore
├── QtCore.so
├── QtGui
├── QtGui.so
├── QtPrintSupport
├── QtSvg
├── QtWidgets
├── QtWidgets.so
├── lib
│   ├── imageformats
│   │   ├── libqdds.dylib
│   │   ├── libqgif.dylib
│   │   ├── libqicns.dylib
│   │   ├── libqico.dylib
│   │   ├── libqjp2.dylib
│   │   ├── libqjpeg.dylib
│   │   ├── libqmng.dylib
│   │   ├── libqsvg.dylib
│   │   ├── libqtga.dylib
│   │   ├── libqtiff.dylib
│   │   ├── libqwbmp.dylib
│   │   └── libqwebp.dylib
│   ├── platforms
│   │   ├── libqcocoa.dylib
│   │   ├── libqminimal.dylib
│   │   └── libqoffscreen.dylib
│   ├── python3.5
│   │   ├── PyQt5.QtCore.so
│   │   ├── PyQt5.QtGui.so
│   │   ├── PyQt5.QtWidgets.so
│   │   ├── _bz2.cpython-35m-darwin.so
│   │   ├── _codecs_cn.cpython-35m-darwin.so
│   │   ├── _codecs_hk.cpython-35m-darwin.so
│   │   ├── _codecs_iso2022.cpython-35m-darwin.so
│   │   ├── _codecs_jp.cpython-35m-darwin.so
│   │   ├── _codecs_kr.cpython-35m-darwin.so
│   │   ├── _codecs_tw.cpython-35m-darwin.so
│   │   ├── _datetime.cpython-35m-darwin.so
│   │   ├── _hashlib.cpython-35m-darwin.so
│   │   ├── _heapq.cpython-35m-darwin.so
│   │   ├── _lzma.cpython-35m-darwin.so
│   │   ├── _md5.cpython-35m-darwin.so
│   │   ├── _multibytecodec.cpython-35m-darwin.so
│   │   ├── _opcode.cpython-35m-darwin.so
│   │   ├── _posixsubprocess.cpython-35m-darwin.so
│   │   ├── _random.cpython-35m-darwin.so
│   │   ├── _sha1.cpython-35m-darwin.so
│   │   ├── _sha256.cpython-35m-darwin.so
│   │   ├── _sha512.cpython-35m-darwin.so
│   │   ├── _socket.cpython-35m-darwin.so
│   │   ├── _ssl.cpython-35m-darwin.so
│   │   ├── _struct.cpython-35m-darwin.so
│   │   ├── binascii.cpython-35m-darwin.so
│   │   ├── grp.cpython-35m-darwin.so
│   │   ├── math.cpython-35m-darwin.so
│   │   ├── pyexpat.cpython-35m-darwin.so
│   │   ├── readline.cpython-35m-darwin.so
│   │   ├── select.cpython-35m-darwin.so
│   │   ├── sip.so
│   │   ├── termios.cpython-35m-darwin.so
│   │   ├── unicodedata.cpython-35m-darwin.so
│   │   └── zlib.cpython-35m-darwin.so
│   └── python35.zip
├── libcrypto.1.0.0.dylib
├── liblzma.5.dylib
├── libqcocoa.dylib
├── libqdds.dylib
├── libqgif.dylib
├── libqicns.dylib
├── libqico.dylib
├── libqjp2.dylib
├── libqjpeg.dylib
├── libqminimal.dylib
├── libqmng.dylib
├── libqoffscreen.dylib
├── libqsvg.dylib
├── libqtga.dylib
├── libqtiff.dylib
├── libqwbmp.dylib
├── libqwebp.dylib
├── libreadline.6.dylib
└── libssl.1.0.0.dylib

4 directories, 80 files

```

and this is the **working** "combined" 4.3.4+5.0

```
#!

uliano@MacPro:~/PycharmProjects/freezeqt5$ tree build/PyQt5app-0.1.app/Contents/MacOS/
build/PyQt5app-0.1.app/Contents/MacOS/
├── PyQt5.QtCore.so
├── PyQt5.QtGui.so
├── PyQt5.QtWidgets.so
├── PyQt5app
├── Python
├── QtCore
├── QtCore.so
├── QtGui
├── QtGui.so
├── QtPrintSupport
├── QtSvg
├── QtWidgets
├── QtWidgets.so
├── _bz2.cpython-35m-darwin.so
├── _codecs_cn.cpython-35m-darwin.so
├── _codecs_hk.cpython-35m-darwin.so
├── _codecs_iso2022.cpython-35m-darwin.so
├── _codecs_jp.cpython-35m-darwin.so
├── _codecs_kr.cpython-35m-darwin.so
├── _codecs_tw.cpython-35m-darwin.so
├── _datetime.cpython-35m-darwin.so
├── _heapq.cpython-35m-darwin.so
├── _multibytecodec.cpython-35m-darwin.so
├── _struct.cpython-35m-darwin.so
├── binascii.cpython-35m-darwin.so
├── imageformats
│   ├── libqdds.dylib
│   ├── libqgif.dylib
│   ├── libqicns.dylib
│   ├── libqico.dylib
│   ├── libqjp2.dylib
│   ├── libqjpeg.dylib
│   ├── libqmng.dylib
│   ├── libqsvg.dylib
│   ├── libqtga.dylib
│   ├── libqtiff.dylib
│   ├── libqwbmp.dylib
│   └── libqwebp.dylib
├── lib
│   ├── imageformats
│   │   ├── libqdds.dylib
│   │   ├── libqgif.dylib
│   │   ├── libqicns.dylib
│   │   ├── libqico.dylib
│   │   ├── libqjp2.dylib
│   │   ├── libqjpeg.dylib
│   │   ├── libqmng.dylib
│   │   ├── libqsvg.dylib
│   │   ├── libqtga.dylib
│   │   ├── libqtiff.dylib
│   │   ├── libqwbmp.dylib
│   │   └── libqwebp.dylib
│   ├── platforms
│   │   ├── libqcocoa.dylib
│   │   ├── libqminimal.dylib
│   │   └── libqoffscreen.dylib
│   ├── python3.5
│   │   ├── PyQt5.QtCore.so
│   │   ├── PyQt5.QtGui.so
│   │   ├── PyQt5.QtWidgets.so
│   │   ├── _bz2.cpython-35m-darwin.so
│   │   ├── _codecs_cn.cpython-35m-darwin.so
│   │   ├── _codecs_hk.cpython-35m-darwin.so
│   │   ├── _codecs_iso2022.cpython-35m-darwin.so
│   │   ├── _codecs_jp.cpython-35m-darwin.so
│   │   ├── _codecs_kr.cpython-35m-darwin.so
│   │   ├── _codecs_tw.cpython-35m-darwin.so
│   │   ├── _datetime.cpython-35m-darwin.so
│   │   ├── _hashlib.cpython-35m-darwin.so
│   │   ├── _heapq.cpython-35m-darwin.so
│   │   ├── _lzma.cpython-35m-darwin.so
│   │   ├── _md5.cpython-35m-darwin.so
│   │   ├── _multibytecodec.cpython-35m-darwin.so
│   │   ├── _opcode.cpython-35m-darwin.so
│   │   ├── _posixsubprocess.cpython-35m-darwin.so
│   │   ├── _random.cpython-35m-darwin.so
│   │   ├── _sha1.cpython-35m-darwin.so
│   │   ├── _sha256.cpython-35m-darwin.so
│   │   ├── _sha512.cpython-35m-darwin.so
│   │   ├── _socket.cpython-35m-darwin.so
│   │   ├── _ssl.cpython-35m-darwin.so
│   │   ├── _struct.cpython-35m-darwin.so
│   │   ├── binascii.cpython-35m-darwin.so
│   │   ├── grp.cpython-35m-darwin.so
│   │   ├── math.cpython-35m-darwin.so
│   │   ├── pyexpat.cpython-35m-darwin.so
│   │   ├── readline.cpython-35m-darwin.so
│   │   ├── select.cpython-35m-darwin.so
│   │   ├── sip.so
│   │   ├── termios.cpython-35m-darwin.so
│   │   ├── unicodedata.cpython-35m-darwin.so
│   │   └── zlib.cpython-35m-darwin.so
│   └── python35.zip
├── libcrypto.1.0.0.dylib
├── liblzma.5.dylib
├── libqcocoa.dylib
├── libqdds.dylib
├── libqgif.dylib
├── libqicns.dylib
├── libqico.dylib
├── libqjp2.dylib
├── libqjpeg.dylib
├── libqminimal.dylib
├── libqmng.dylib
├── libqoffscreen.dylib
├── libqsvg.dylib
├── libqtga.dylib
├── libqtiff.dylib
├── libqwbmp.dylib
├── libqwebp.dylib
├── library.zip
├── libreadline.6.dylib
├── libssl.1.0.0.dylib
├── math.cpython-35m-darwin.so
├── platforms
│   ├── libqcocoa.dylib
│   ├── libqminimal.dylib
│   └── libqoffscreen.dylib
├── sip.so
├── unicodedata.cpython-35m-darwin.so
└── zlib.cpython-35m-darwin.so

6 directories, 115 files

```

It should be noted that running the other way around: first 5.0 and then 4.3.4 doesn't work with same result as 4.3.4 alone while the tree directory is the same of the combined working example

I guess that the explanation should be here in front of my eyes, but I miss it. 

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/170

**Comment by anthony-tuininga** [comment]
*Original comment by* **uliano guerrini (Bitbucket: [uguerrini](https://bitbucket.org/uguerrini), GitHub: Unknown)**:

----------------------------------------

Found my way out:

first I downgraded to python3.4.3 to get rid of 

`AttributeError: module 'imp' has no attribute 'load_dynamic'`

but  qt couldn't find `libqcocoa.dylib` because the plugins folder should be outside the `lib` directory

so I fixed this building with following shell script


```
#!sh

#!/usr/bin/env bash
rm -fr build
python3 setupcx.py bdist_mac --qt-menu-nib=/usr/local/opt/qt5/plugins/platforms
cd build/*.app/Contents/MacOs
mv lib/platforms .
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
