### ISSUE TITLE
cx_freeze not able to import pandastable package

### ISSUE THREAD

**Issue by priyanka22kar** [marcelotduarte/cx_Freeze#396]
import cx_Freeze
import sys
import os

if sys.platform == 'win32':
    base = "Win32GUI"

executables = [cx_Freeze.Executable("Cm.py",icon = "48 size.ico", base="Win32GUI")]

PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tk8.6')

options = {'build_exe': {"packages": ["os","pandastable"], "includes": ["idna.idnadata"],
                         'include_files': [os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tk86t.dll'),

                              os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tcl86t.dll'), ], }, }
cx_Freeze.setup(name='MongodbUpdation', version="1.0", description='MongoDB Updation',
                options=options, executables=executables)

this is my setup file 
I have used pandas table package for my tkinter GUI application
It executes perfectly but when I try to build an application of the same using cxfreeze it gives me an error saying pandastable cannot be imported 
what can I do to solve the issue ?
please help @ambrice @kingb @ciromattia @bfroehle @takluyver 
thank you

**Comment by marcelotduarte** [comment]
PR #559 solves issues with tkinter.
You can remove the workaround related to include tcl/tk libraries.

cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by SylvanusMounk** [comment]
Hello, I'm having the same problem with Pandastable module if i'm compiling my script with cx_freeze. I'm working with Windows32, Python3.8 and my cx_freeze version is 6.5.3
Here is :
ImportError: cannot import name 'util' from partially initialized module 'pandastable' (most likely due to a circular import)
please help me.

**Comment by marcelotduarte** [comment]
@SylvanusMounk Please open a new issue. If you can, provide a setup and sample test.

**Comment by SylvanusMounk** [comment]
Ok, but I don't know how to create it!

**Comment by marcelotduarte** [comment]
https://github.com/marcelotduarte/cx_Freeze/issues/new

**Comment by SylvanusMounk** [comment]
Ok thanks, l have already it done.
