### ISSUE TITLE
matplotlib.libs folder is not copied/searched at correct location by cx_Freeze 

### ISSUE THREAD

**Issue by borisb39** [marcelotduarte/cx_Freeze#1889]
**Describe the bug**
Similar issue than #1789 but when zip folder is used:
"FileNotFoundError: [WinError 2]: No such file: C:\Users\....\build\zip.win-amd64-3.9\lib\library.zip\matplotlib.libs".
matplotlib.libs is copied under build\\zip.win-amd64-3.9\\lib\\matplotlib.libs and searched under build\\zip.win-amd64-3.9\\lib\\library.zip\\matplotlib.libs.

**To Reproduce**
Run setup_zip.py in cx_Freeze/samples/matplotlib: py -3.9 setup_zip.py build
Run frozen matplotlib_eg.exe

**Desktop**
Platform information: Windows 10 20H2
OS architecture: 64-bit
cx_Freeze version: 6.15.0
Python version: 3.9.12
matplotlib version: 3.7.1

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by dcnieho** [comment]
Solves the problem for me. But i get the same error for scipy.libs (scipy version 1.10.1)

**Comment by borisb39** [comment]
Issue solved on my side too. Thanks !

**Comment by marcelotduarte** [comment]
[Release 6.15.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.1)

**Comment by borisb39** [comment]
Hello,

I tried the release 6.15.1 with the same test case.
Unfortunaltelly I got the error : 
"cannot import name 'multiarray' from partially initialized module 'numpy.core'"
and couldn't confirm that everything is fine.

I tried the workarounds:
"zip_exclude_packages": ["numpy"]
or 
"packages": ["numpy"]
with no effect.

With cx_freeze 6.16.0dev1 this issue is not raised (with or without "zip_exclude_packages": ["numpy"] ).

Should I create a dedicated ticket for 6.15.xx or wait for the first 6.16.xx release?

**Comment by dcnieho** [comment]
I have the same issue with the release. numpy version wrongly packaged is 1.24.3. The issue seems to be almost all the .pyc files of numpy are missing. See this screenshot which is the contents of the /numpy/core folder that is broken:
![image](https://github.com/marcelotduarte/cx_Freeze/assets/1787673/f7a8f384-c415-45ed-8eea-5ed9156d5ada)
And this (part) of what it looked like for the working version from the dev version i tested before the release:
![image](https://github.com/marcelotduarte/cx_Freeze/assets/1787673/93acc478-098a-4318-b22c-154a34a6f51a)

**Comment by dcnieho** [comment]
I see now that the .pyc files are in the zip folder, like reported here: #1907

**Comment by marcelotduarte** [comment]
PR #1922 fixes #1907 and #1912
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

I'll release 6.15.2 soon.

**Comment by borisb39** [comment]
Thank you for the support. Still working fine with 6.16.0dev1 from the link above.

**Comment by dcnieho** [comment]
I'm on holiday so won't be able to test soon, hope one test is enough and
you can release soon!

**Comment by marcelotduarte** [comment]
[Release 6.15.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.2)

**Comment by borisb39** [comment]
6.15.2 is working fine. Thank you !
