### ISSUE TITLE
Incompatibility with Pyqt5.9

### ISSUE THREAD

**Issue by zbuh** [marcelotduarte/cx_Freeze#288]
(Ubuntu 16.04.2)
After upgrading Pyqt5 from 5.8 to 5.9.
got: "WARNING: Tried to load multiple incompatible Qt wrappers. Some incorrect files may be copied."

and breaks with
  File "/mnt/raid/jenkins/workspace/jig/jig/.venv/lib/python3.5/site-packages/cx_Freeze/hooks.py", line 525, in load_PyQt4_QtGui
    _QtGui(finder, module, QtCore.QT_VERSION_STR)
AttributeError: 'NoneType' object has no attribute 'QT_VERSION_STR'

**Comment by anthony-tuininga** [comment]
It seems like you are trying to load both PyQt4 and PyQt5? That can happen if a PyQt wrapper tries to load PyQt5 and if that can't be found, tries to load PyQt4. You can explicitly exclude PyQt4 in that case. Failing that, can you provide a test case?

**Comment by anthony-tuininga** [comment]
Closing due to lack of response.
